spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/elearning_db
    username: postgres
    password: 123079
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org.springframework.security: trace
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include: health, caches, info, metrics

server:
  port: 8080

file:
  server-path: D:/upload-files/
  client-path: /api/wba/v1/image
  base-url: http://localhost:8080${file.client-path}